variables:
  SSH_HOST: "0.tcp.ap.ngrok.io"
  SSH_USER: "aimo"
  SSH_PORT: "10484"  # Default SSH port

stages:
  - test

test_ssh_connection:
  stage: test
  script:
    - mkdir -p $HOME/.ssh
    - echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
    - chmod 600 $HOME/.ssh/id_rsa
    - echo "$HOME"
    - ssh -o IdentitiesOnly=yes -i $HOME/.ssh/id_rsa -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo 'SSH connection successful!'"

