from .variable import VariableResource, VariablesResource
from .variable_causes import VariableCauseResource, VariableCausesResource
from .variable_headers import VariableHeaderResource, VariableHeadersResource
