from .variable import VariableResource, VariablesResource, VariableDataAddResource
from .variable_causes import VariableCauseResource, VariableCausesResource, VariableCauseActionResource
from .variable_headers import VariableHeaderResource, VariableHeadersResource
